"""increase length of image url field

Revision ID: 41365db0a4c5
Revises: f143eefbc305
Create Date: 2024-10-31 00:25:51.774177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41365db0a4c5'
down_revision = 'f143eefbc305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
